/// <reference path="../../Scripts/objects/game.ts"/>
/// <reference path="../../Scripts/objects/label.ts"/>
/// <reference path="../../Scripts/objects/button.ts"/>
/// <reference path="../../Scripts/config/scene.ts"/>
/// <reference path="../../Scripts/objects/scene.ts"/>
/// <reference path="../../Scripts/Scenes/start.ts"/>
/// <reference path="../../Scripts/Scenes/over.ts"/>
/// <reference path="../../Scripts/Scenes/play.ts"/>
/// <reference path="../../Scripts/Scenes/start.ts"/>
//# sourceMappingURL=_references.js.map